name: desafio_flutter
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  image_picker: ^1.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/logo.png
    - assets/images/logo_create.png
    - assets/images/google.png
    - assets/images/apple.png
    - assets/images/image_camera.png
    - assets/images/movie_mock.png
    - assets/images/send.png
    - assets/images/like.png
    - assets/images/profile_mock.png
    - assets/images/duble_like.png
    - assets/images/unlike.png
  uses-material-design: true
